"""Install shell tab-completion scripts into the repo checkout."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

import click

from .self_update import project_root

MARKER_START = "# >>> {prog} completions >>>"
MARKER_END = "# <<< {prog} completions <<<"
GITIGNORE_ENTRY = "completions/"


@dataclass(frozen=True)
class InstallResult:
    """Paths touched by a completion install."""

    repo_root: Path
    completion_file: Path
    shell_rc: Path
    shell: str
    prog_name: str


def generate_script(*, shell: str, prog_name: str, cli_group: click.Group) -> str:
    """Return the Click-generated completion script for a shell."""
    from click.shell_completion import get_completion_class

    shell_class = get_completion_class(shell)
    if shell_class is None:
        raise click.ClickException(f"Unsupported shell: {shell}")

    env_var = f"_{prog_name.replace('-', '_').upper()}_COMPLETE"
    script = shell_class(cli_group, {}, prog_name, env_var).source()
    if not script.endswith("\n"):
        script += "\n"
    return script


def completion_relpath(shell: str, prog_name: str) -> Path:
    """Relative path of the completion file inside the repo."""
    if shell == "zsh":
        return Path("completions") / f"_{prog_name}"
    if shell == "bash":
        return Path("completions") / f"{prog_name}.bash"
    return Path("completions") / f"{prog_name}.fish"


def shell_rc_path(shell: str) -> Path:
    """Default rc file for the user's shell."""
    home = Path.home()
    if shell == "zsh":
        return home / ".zshrc"
    if shell == "bash":
        return home / ".bashrc"
    return home / ".config/fish/config.fish"


def _markers(prog_name: str) -> tuple[str, str]:
    return (
        MARKER_START.format(prog=prog_name),
        MARKER_END.format(prog=prog_name),
    )


def _snippet(shell: str, prog_name: str, completion_file: Path) -> str:
    """Rc-file lines that source the repo-local completion script."""
    path = str(completion_file.resolve())
    start, end = _markers(prog_name)
    if shell == "fish":
        body = f"test -f '{path}'; and source '{path}'"
    else:
        body = f"[[ -f '{path}' ]] && source '{path}'"
    return f"\n{start}\n{body}\n{end}\n"


_LEGACY_INLINE_ZSH = re.compile(
    r"\n# tm (?:tab )?(?:shell )?completion[^\n]*\n#compdef tm\n.*?\nfi\n",
    re.DOTALL,
)


def _strip_legacy_inline_zsh(content: str) -> str:
    """Remove an old-style completion block pasted directly into .zshrc."""
    return _LEGACY_INLINE_ZSH.sub("", content)


def _strip_marked_block(content: str, prog_name: str) -> str:
    """Remove a previous install block for ``prog_name``, if present."""
    start, end = _markers(prog_name)
    pattern = re.compile(
        rf"\n?{re.escape(start)}.*?{re.escape(end)}\n?",
        re.DOTALL,
    )
    content = pattern.sub("", content)
    return _strip_legacy_inline_zsh(content)


def ensure_gitignore(repo_root: Path) -> bool:
    """Append ``completions/`` to .gitignore when missing. Returns True if changed."""
    gitignore = repo_root / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(
            f"# Shell completions (generated by tm completions)\n{GITIGNORE_ENTRY}\n"
        )
        return True

    text = gitignore.read_text(encoding="utf-8")
    if GITIGNORE_ENTRY in text.splitlines():
        return False

    suffix = "" if text.endswith("\n") else "\n"
    gitignore.write_text(
        f"{text}{suffix}\n# Shell completions (generated by tm completions)\n{GITIGNORE_ENTRY}\n",
        encoding="utf-8",
    )
    return True


def update_shell_rc(
    *,
    shell: str,
    prog_name: str,
    completion_file: Path,
    shell_rc: Path | None = None,
) -> Path:
    """Write or replace the marked source block in the user's shell rc."""
    rc_path = shell_rc or shell_rc_path(shell)
    snippet = _snippet(shell, prog_name, completion_file)

    if rc_path.exists():
        content = rc_path.read_text(encoding="utf-8")
    else:
        content = ""
        rc_path.parent.mkdir(parents=True, exist_ok=True)

    content = _strip_marked_block(content, prog_name)
    if content and not content.endswith("\n"):
        content += "\n"
    rc_path.write_text(content + snippet, encoding="utf-8")
    return rc_path


def install(
    *,
    shell: str,
    prog_name: str,
    cli_group: click.Group,
    repo_root: Path | None = None,
    shell_rc: Path | None = None,
) -> InstallResult:
    """Write completion script into the repo and wire the shell rc to source it."""
    root = repo_root or project_root()
    if root is None:
        raise click.ClickException(
            "Could not find a track-manager source checkout.\n"
            "Shell completion install only works for editable installs from git.\n"
            "Use: tm completions --print zsh  (print script to stdout instead)"
        )

    rel = completion_relpath(shell, prog_name)
    completion_file = root / rel
    completion_file.parent.mkdir(parents=True, exist_ok=True)
    completion_file.write_text(
        generate_script(shell=shell, prog_name=prog_name, cli_group=cli_group),
        encoding="utf-8",
    )

    ensure_gitignore(root)
    rc_path = update_shell_rc(
        shell=shell,
        prog_name=prog_name,
        completion_file=completion_file,
        shell_rc=shell_rc,
    )

    return InstallResult(
        repo_root=root,
        completion_file=completion_file,
        shell_rc=rc_path,
        shell=shell,
        prog_name=prog_name,
    )
