"""Unit tests for shell_completions install helpers."""

from pathlib import Path

from track_manager.cli import cli
from track_manager.shell_completions import (
    GITIGNORE_ENTRY,
    ensure_gitignore,
    generate_script,
    install,
    update_shell_rc,
)


def test_generate_script_zsh_starts_with_compdef() -> None:
    script = generate_script(shell="zsh", prog_name="tm", cli_group=cli)
    assert script.startswith("#compdef tm\n")


def test_ensure_gitignore_appends_once(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / ".gitignore").write_text("config.yaml\n")

    assert ensure_gitignore(repo) is True
    text = (repo / ".gitignore").read_text()
    assert GITIGNORE_ENTRY in text

    assert ensure_gitignore(repo) is False


def test_update_shell_rc_replaces_marked_block(tmp_path: Path) -> None:
    rc = tmp_path / ".zshrc"
    completion = tmp_path / "completions" / "_tm"
    completion.parent.mkdir()
    completion.write_text("#compdef tm\n")

    rc.write_text('eval "$(pyenv init - zsh)"')
    update_shell_rc(
        shell="zsh",
        prog_name="tm",
        completion_file=completion,
        shell_rc=rc,
    )
    first = rc.read_text()
    assert "# >>> tm completions >>>" in first
    assert str(completion.resolve()) in first

    update_shell_rc(
        shell="zsh",
        prog_name="tm",
        completion_file=completion,
        shell_rc=rc,
    )
    second = rc.read_text()
    assert second.count("# >>> tm completions >>>") == 1


def test_update_shell_rc_strips_legacy_inline_block(tmp_path: Path) -> None:
    rc = tmp_path / ".zshrc"
    completion = tmp_path / "completions" / "_tm"
    completion.parent.mkdir(parents=True)
    completion.write_text("#compdef tm\n")

    rc.write_text(
        'eval "$(pyenv init - zsh)"\n\n'
        "# tm tab completion (generated by: tm completions zsh)\n"
        "#compdef tm\n\n"
        "_tm_completion() {\n"
        "  true\n"
        "}\n\n"
        "compdef _tm_completion tm\n"
        "fi\n"
    )
    update_shell_rc(
        shell="zsh",
        prog_name="tm",
        completion_file=completion,
        shell_rc=rc,
    )
    text = rc.read_text()
    assert "_tm_completion() {" not in text
    assert "# >>> tm completions >>>" in text


def test_install_writes_repo_files(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "pyproject.toml").write_text("[project]\nname='track-manager'\n")
    rc = tmp_path / ".zshrc"
    rc.write_text("")

    result = install(
        shell="zsh",
        prog_name="tm",
        cli_group=cli,
        repo_root=repo,
        shell_rc=rc,
    )

    assert result.completion_file.is_file()
    assert result.completion_file.read_text().startswith("#compdef tm")
    assert GITIGNORE_ENTRY in (repo / ".gitignore").read_text()
    assert "# >>> tm completions >>>" in rc.read_text()
